[package]
name = "keytool"
authors = ['Clover Network <https://github.com/clover-network>']
edition = '2018'
license = 'GPL-3.0'
homepage = 'https://clover.finance'
repository = 'https://github.com/clover-network/clover'
version = '0.9.0'

[[bin]]
name = "keytool"
path = "src/main.rs"

[dependencies]
structopt = "0.3.8"
secp256k1 = "0.20.3"
tiny-bip39 = "0.8.0"
tiny-hderive = "0.3.0"
sha3 = { version = "0.9.1", default-features = false }
sp-core = { git = "https://github.com/paritytech/substrate.git",  tag = "v3.0.0" , default-features = false }
sp-runtime = { git = "https://github.com/paritytech/substrate.git",  tag = "v3.0.0" , default-features = false }