name: Clover ivy deploy
on:
  push:
    tags:
      - ivy-*
jobs:
  build-and-publish-ivy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Set release version env
        run: echo "RELEASE_VER=$(echo ${GITHUB_REF#refs/*/}  | cut -d '-' -f 2 )" >> $GITHUB_ENV
      - uses: actions/cache@v2
        with:
          path: |
            .local
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - run: |
             touch .env.ci
             echo CLOVER_NETWORK="clover-mainnet" > .env.ci
      - run: docker-compose --env-file .env.ci up build && cp -f target_linux/clover docker/
      - run: rm -rf docker/specs && cp -r specs/ docker/

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: ./docker
          file: ./docker/Dockerfile
          push: true
          tags: cloverio/clover-ivy:${{ env.RELEASE_VER }}
